// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimWinReducer from "../claim_win_reducer";
import CreateLobbyReducer from "../create_lobby_reducer";
import CreatePracticeReducer from "../create_practice_reducer";
import CreateTournamentReducer from "../create_tournament_reducer";
import ForfeitReducer from "../forfeit_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import KickReducer from "../kick_reducer";
import KickReleaseReducer from "../kick_release_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import PlaceBetReducer from "../place_bet_reducer";
import RematchReducer from "../rematch_reducer";
import SendChatReducer from "../send_chat_reducer";
import SendEmoteReducer from "../send_emote_reducer";
import SetCharacterReducer from "../set_character_reducer";
import SetInputReducer from "../set_input_reducer";
import SetNameReducer from "../set_name_reducer";
import SetTournamentSettingsReducer from "../set_tournament_settings_reducer";
import SpectateMatchReducer from "../spectate_match_reducer";
import StartTournamentReducer from "../start_tournament_reducer";
import TackleReducer from "../tackle_reducer";

export type ClaimWinParams = __Infer<typeof ClaimWinReducer>;
export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type CreatePracticeParams = __Infer<typeof CreatePracticeReducer>;
export type CreateTournamentParams = __Infer<typeof CreateTournamentReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type KickParams = __Infer<typeof KickReducer>;
export type KickReleaseParams = __Infer<typeof KickReleaseReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type PlaceBetParams = __Infer<typeof PlaceBetReducer>;
export type RematchParams = __Infer<typeof RematchReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SendEmoteParams = __Infer<typeof SendEmoteReducer>;
export type SetCharacterParams = __Infer<typeof SetCharacterReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetTournamentSettingsParams = __Infer<typeof SetTournamentSettingsReducer>;
export type SpectateMatchParams = __Infer<typeof SpectateMatchReducer>;
export type StartTournamentParams = __Infer<typeof StartTournamentReducer>;
export type TackleParams = __Infer<typeof TackleReducer>;

