// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string().name("display_name"),
  characterId: __t.u8().name("character_id"),
  xp: __t.u32(),
  level: __t.u16(),
  mmr: __t.u16(),
  peakMmr: __t.u16().name("peak_mmr"),
  ranked: __t.u16(),
  rankedWins: __t.u16().name("ranked_wins"),
  casual: __t.u16(),
  casualWins: __t.u16().name("casual_wins"),
  streak: __t.i16(),
  bestStreak: __t.u16().name("best_streak"),
  quits: __t.u16(),
  createdAt: __t.timestamp().name("created_at"),
  lastSeen: __t.timestamp().name("last_seen"),
});
