// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  active: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  lastHitSide: __t.u8().name("last_hit_side"),
  bounces: __t.u8(),
  rallyHits: __t.u8().name("rally_hits"),
  spinX: __t.f32().name("spin_x"),
  aimGraceTicks: __t.u8().name("aim_grace_ticks"),
  aimQuality: __t.u8().name("aim_quality"),
  aimKind: __t.u8().name("aim_kind"),
  aimBehind: __t.bool().name("aim_behind"),
  aimContactZ: __t.f32().name("aim_contact_z"),
  aimDriftBase: __t.f32().name("aim_drift_base"),
  aimLeadY: __t.f32().name("aim_lead_y"),
  apexZ: __t.f32().name("apex_z"),
  aimApexZ: __t.f32().name("aim_apex_z"),
  freezeTicks: __t.u8().name("freeze_ticks"),
});
