// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  matchId: __t.u64().name("match_id"),
  bettor: __t.identity(),
  bettorName: __t.string().name("bettor_name"),
  side: __t.u8(),
  stake: __t.u32(),
  oddsMilli: __t.u32().name("odds_milli"),
  state: __t.u8(),
  payout: __t.u32(),
  placedAt: __t.timestamp().name("placed_at"),
});
