// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  lobbyId: __t.u64().name("lobby_id"),
  open: __t.bool(),
  priorMilli: __t.u32().name("prior_milli"),
  seed0: __t.u32().name("seed_0"),
  seed1: __t.u32().name("seed_1"),
  pool0: __t.u32().name("pool_0"),
  pool1: __t.u32().name("pool_1"),
  odds0Milli: __t.u32().name("odds_0_milli"),
  odds1Milli: __t.u32().name("odds_1_milli"),
});
