// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  pitch: __t.u8(),
  isPublic: __t.bool(),
  teamSize: __t.u8(),
  gravityMul: __t.f32(),
  frictionMul: __t.f32(),
  powerMul: __t.f32(),
  bounceMul: __t.f32(),
};
