// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  court: __t.u8(),
  ruleset: __t.u8(),
  botLevel: __t.u8(),
  gravityMul: __t.f32(),
  dragMul: __t.f32(),
  speedMul: __t.f32(),
  bounceMul: __t.f32(),
};
