// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  lobbyId: __t.u64().name("lobby_id"),
  side: __t.u8(),
  scorerName: __t.string().name("scorer_name"),
  ownGoal: __t.bool().name("own_goal"),
  half: __t.u8(),
  clockSecs: __t.u16().name("clock_secs"),
  at: __t.timestamp(),
});
