// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostId: __t.identity().name("host_id"),
  mode: __t.u8(),
  status: __t.u8(),
  vsBot: __t.bool().name("vs_bot"),
  pitch: __t.u8(),
  concurrent: __t.u8(),
  championName: __t.string().name("champion_name"),
  createdAt: __t.timestamp().name("created_at"),
  botLevel: __t.u8().name("bot_level"),
  gravityMul: __t.f32().name("gravity_mul"),
  frictionMul: __t.f32().name("friction_mul"),
  powerMul: __t.f32().name("power_mul"),
  bounceMul: __t.f32().name("bounce_mul"),
  isPublic: __t.bool().name("is_public"),
  format: __t.u8(),
  teamSize: __t.u8().name("team_size"),
  betWinnerName: __t.string().name("bet_winner_name"),
  betWinnerCredits: __t.u32().name("bet_winner_credits"),
  championshipLeg: __t.u64().name("championship_leg"),
});
