// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  round: __t.u8(),
  slot: __t.u8(),
  state: __t.u8(),
  p0Id: __t.identity().name("p_0_id"),
  p1Id: __t.identity().name("p_1_id"),
  hasP1: __t.bool().name("has_p_1"),
  phase: __t.u8(),
  p0Points: __t.u8().name("p_0_points"),
  p1Points: __t.u8().name("p_1_points"),
  p0Games: __t.u8().name("p_0_games"),
  p1Games: __t.u8().name("p_1_games"),
  gamesToWin: __t.u8().name("games_to_win"),
  servingSide: __t.u8().name("serving_side"),
  pauseTicks: __t.u16().name("pause_ticks"),
  pointMsg: __t.string().name("point_msg"),
  winnerSide: __t.u8().name("winner_side"),
  rematchVotes: __t.u8().name("rematch_votes"),
  startTicks: __t.u16().name("start_ticks"),
  bracket: __t.u8(),
  p0Sets: __t.u8().name("p_0_sets"),
  p1Sets: __t.u8().name("p_1_sets"),
  p0PtsTotal: __t.u16().name("p_0_pts_total"),
  p1PtsTotal: __t.u16().name("p_1_pts_total"),
  haltMask: __t.u8().name("halt_mask"),
  haltedAt: __t.u64().name("halted_at"),
  haltUntil: __t.u64().name("halt_until"),
  haltName: __t.string().name("halt_name"),
});
