// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  round: __t.u8(),
  slot: __t.u8(),
  state: __t.u8(),
  p0Id: __t.identity().name("p_0_id"),
  p1Id: __t.identity().name("p_1_id"),
  hasP1: __t.bool().name("has_p_1"),
  phase: __t.u8(),
  p0Goals: __t.u8().name("p_0_goals"),
  p1Goals: __t.u8().name("p_1_goals"),
  half: __t.u8(),
  clockTicks: __t.u32().name("clock_ticks"),
  kickoffSide: __t.u8().name("kickoff_side"),
  restartKind: __t.u8().name("restart_kind"),
  restartSide: __t.u8().name("restart_side"),
  restartX: __t.f32().name("restart_x"),
  restartY: __t.f32().name("restart_y"),
  graceTicks: __t.u8().name("grace_ticks"),
  pauseTicks: __t.u16().name("pause_ticks"),
  pointMsg: __t.string().name("point_msg"),
  winnerSide: __t.u8().name("winner_side"),
  rematchVotes: __t.u8().name("rematch_votes"),
  startTicks: __t.u16().name("start_ticks"),
  bracket: __t.u8(),
  haltMask: __t.u8().name("halt_mask"),
  haltedAt: __t.u64().name("halted_at"),
  haltUntil: __t.u64().name("halt_until"),
  haltName: __t.string().name("halt_name"),
  presser0: __t.u8().name("presser_0"),
  presser1: __t.u8().name("presser_1"),
  possSide: __t.u8().name("poss_side"),
  transTicks: __t.u8().name("trans_ticks"),
});
