// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  matchId: __t.u64().name("match_id"),
  opponentName: __t.string().name("opponent_name"),
  won: __t.bool(),
  ranked: __t.bool(),
  mmrBefore: __t.u16().name("mmr_before"),
  mmrAfter: __t.u16().name("mmr_after"),
  xpBefore: __t.u32().name("xp_before"),
  xpGained: __t.u32().name("xp_gained"),
  levelAfter: __t.u16().name("level_after"),
  goalsFor: __t.u8().name("goals_for"),
  goalsAgainst: __t.u8().name("goals_against"),
  endedBy: __t.u8().name("ended_by"),
  playedAt: __t.timestamp().name("played_at"),
});
