// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  lobbyId: __t.u64().name("lobby_id"),
  matchId: __t.u64().name("match_id"),
  side: __t.u8(),
  eliminated: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  dirX: __t.i8().name("dir_x"),
  dirY: __t.i8().name("dir_y"),
  sprinting: __t.bool(),
  kickTicks: __t.u8().name("kick_ticks"),
  kickKind: __t.u8().name("kick_kind"),
  kickHeld: __t.bool().name("kick_held"),
  slideTicks: __t.u8().name("slide_ticks"),
  slideDirX: __t.f32().name("slide_dir_x"),
  slideDirY: __t.f32().name("slide_dir_y"),
  stamina: __t.u16(),
  role: __t.u8(),
  characterId: __t.u8().name("character_id"),
  online: __t.bool(),
  isBot: __t.bool().name("is_bot"),
  spectator: __t.bool(),
  teamSlot: __t.u8().name("team_slot"),
  ctrlSeat: __t.u8().name("ctrl_seat"),
  switchLock: __t.u8().name("switch_lock"),
  matchBot: __t.bool().name("match_bot"),
  switchIdx: __t.u8().name("switch_idx"),
  mvX: __t.f32().name("mv_x"),
  mvY: __t.f32().name("mv_y"),
  holdTicks: __t.u8().name("hold_ticks"),
  velX: __t.f32().name("vel_x"),
  velY: __t.f32().name("vel_y"),
  cards: __t.u8(),
  sentOff: __t.bool().name("sent_off"),
  diveTicks: __t.u8().name("dive_ticks"),
  diveDirX: __t.f32().name("dive_dir_x"),
  diveDirY: __t.f32().name("dive_dir_y"),
});
