// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  lobbyId: __t.u64().name("lobby_id"),
  matchId: __t.u64().name("match_id"),
  side: __t.u8(),
  eliminated: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  dirX: __t.i8().name("dir_x"),
  dirY: __t.i8().name("dir_y"),
  swingTicks: __t.u8().name("swing_ticks"),
  swingKind: __t.u8().name("swing_kind"),
  swingHeld: __t.bool().name("swing_held"),
  lungeTicks: __t.u8().name("lunge_ticks"),
  characterId: __t.u8().name("character_id"),
  momentum: __t.u16(),
  online: __t.bool(),
  isBot: __t.bool().name("is_bot"),
  spectator: __t.bool(),
  teamSlot: __t.u8().name("team_slot"),
});
