// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string(),
  characterId: __t.u8(),
  xp: __t.u32(),
  level: __t.u16(),
  mmr: __t.u16(),
  peakMmr: __t.u16(),
  ranked: __t.u16(),
  rankedWins: __t.u16(),
  casual: __t.u16(),
  casualWins: __t.u16(),
  streak: __t.i16(),
  bestStreak: __t.u16(),
  quits: __t.u16(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const Ball = __t.object("Ball", {
  matchId: __t.u64(),
  active: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  lastTouchSide: __t.u8(),
  lastTouchId: __t.identity(),
  ownerId: __t.identity(),
  hasOwner: __t.bool(),
  lockTicks: __t.u8(),
});
export type Ball = __Infer<typeof Ball>;

export const Bet = __t.object("Bet", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  matchId: __t.u64(),
  bettor: __t.identity(),
  bettorName: __t.string(),
  side: __t.u8(),
  stake: __t.u32(),
  oddsMilli: __t.u32(),
  state: __t.u8(),
  payout: __t.u32(),
  placedAt: __t.timestamp(),
});
export type Bet = __Infer<typeof Bet>;

export const Book = __t.object("Book", {
  matchId: __t.u64(),
  lobbyId: __t.u64(),
  open: __t.bool(),
  priorMilli: __t.u32(),
  seed0: __t.u32(),
  seed1: __t.u32(),
  pool0: __t.u32(),
  pool1: __t.u32(),
  odds0Milli: __t.u32(),
  odds1Milli: __t.u32(),
});
export type Book = __Infer<typeof Book>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  senderSide: __t.u8(),
  senderName: __t.string(),
  emote: __t.bool(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const ChatGuard = __t.object("ChatGuard", {
  identity: __t.identity(),
  windowStart: __t.u64(),
  windowCount: __t.u8(),
  lastAt: __t.u64(),
  lastText: __t.string(),
});
export type ChatGuard = __Infer<typeof ChatGuard>;

export const GoalEvent = __t.object("GoalEvent", {
  id: __t.u64(),
  matchId: __t.u64(),
  lobbyId: __t.u64(),
  side: __t.u8(),
  scorerName: __t.string(),
  ownGoal: __t.bool(),
  half: __t.u8(),
  clockSecs: __t.u16(),
  at: __t.timestamp(),
});
export type GoalEvent = __Infer<typeof GoalEvent>;

export const GraceTimer = __t.object("GraceTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type GraceTimer = __Infer<typeof GraceTimer>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  code: __t.string(),
  hostId: __t.identity(),
  mode: __t.u8(),
  status: __t.u8(),
  vsBot: __t.bool(),
  pitch: __t.u8(),
  concurrent: __t.u8(),
  championName: __t.string(),
  createdAt: __t.timestamp(),
  botLevel: __t.u8(),
  gravityMul: __t.f32(),
  frictionMul: __t.f32(),
  powerMul: __t.f32(),
  bounceMul: __t.f32(),
  isPublic: __t.bool(),
  format: __t.u8(),
  teamSize: __t.u8(),
  betWinnerName: __t.string(),
  betWinnerCredits: __t.u32(),
});
export type Lobby = __Infer<typeof Lobby>;

export const Match = __t.object("Match", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  round: __t.u8(),
  slot: __t.u8(),
  state: __t.u8(),
  p0Id: __t.identity(),
  p1Id: __t.identity(),
  hasP1: __t.bool(),
  phase: __t.u8(),
  p0Goals: __t.u8(),
  p1Goals: __t.u8(),
  half: __t.u8(),
  clockTicks: __t.u32(),
  kickoffSide: __t.u8(),
  restartKind: __t.u8(),
  restartSide: __t.u8(),
  restartX: __t.f32(),
  restartY: __t.f32(),
  graceTicks: __t.u8(),
  pauseTicks: __t.u16(),
  pointMsg: __t.string(),
  winnerSide: __t.u8(),
  rematchVotes: __t.u8(),
  startTicks: __t.u16(),
  bracket: __t.u8(),
  haltMask: __t.u8(),
  haltedAt: __t.u64(),
  haltUntil: __t.u64(),
  haltName: __t.string(),
  presser0: __t.u8(),
  presser1: __t.u8(),
});
export type Match = __Infer<typeof Match>;

export const MatchLog = __t.object("MatchLog", {
  id: __t.u64(),
  identity: __t.identity(),
  matchId: __t.u64(),
  opponentName: __t.string(),
  won: __t.bool(),
  ranked: __t.bool(),
  mmrBefore: __t.u16(),
  mmrAfter: __t.u16(),
  xpBefore: __t.u32(),
  xpGained: __t.u32(),
  levelAfter: __t.u16(),
  goalsFor: __t.u8(),
  goalsAgainst: __t.u8(),
  endedBy: __t.u8(),
  playedAt: __t.timestamp(),
});
export type MatchLog = __Infer<typeof MatchLog>;

export const MyMatchLog = __t.object("MyMatchLog", {});
export type MyMatchLog = __Infer<typeof MyMatchLog>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  lobbyId: __t.u64(),
  matchId: __t.u64(),
  side: __t.u8(),
  eliminated: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  dirX: __t.i8(),
  dirY: __t.i8(),
  sprinting: __t.bool(),
  kickTicks: __t.u8(),
  kickKind: __t.u8(),
  kickHeld: __t.bool(),
  slideTicks: __t.u8(),
  slideDirX: __t.f32(),
  slideDirY: __t.f32(),
  stamina: __t.u16(),
  role: __t.u8(),
  characterId: __t.u8(),
  online: __t.bool(),
  isBot: __t.bool(),
  spectator: __t.bool(),
  teamSlot: __t.u8(),
  ctrlSeat: __t.u8(),
  switchLock: __t.u8(),
  matchBot: __t.bool(),
  switchIdx: __t.u8(),
  mvX: __t.f32(),
  mvY: __t.f32(),
});
export type Player = __Infer<typeof Player>;

export const ReapTimer = __t.object("ReapTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
});
export type ReapTimer = __Infer<typeof ReapTimer>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  startedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const Team = __t.object("Team", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  captainId: __t.identity(),
  memberId: __t.identity(),
  slot: __t.u8(),
});
export type Team = __Infer<typeof Team>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const Wallet = __t.object("Wallet", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  identity: __t.identity(),
  balance: __t.u32(),
  staked: __t.u32(),
  won: __t.u32(),
  lost: __t.u32(),
});
export type Wallet = __Infer<typeof Wallet>;

